backend:
  name: git-gateway
  branch: main

media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "src/data/homepage.json"
        label: "Homepage Content"
        name: "homepage"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Hero Section", name: "hero", widget: "object", fields: [
              { label: "Heading", name: "heading", widget: "string" },
              { label: "Subheading", name: "subheading", widget: "string" }
            ]}
          - { label: "Services", name: "services", widget: "list", fields: [
              { label: "Title", name: "title", widget: "string" },
              { label: "Description", name: "description", widget: "text" },
              { label: "Icon Path", name: "icon", widget: "image", required: false }
            ]}
          - { label: "Map Embed URL", name: "map", widget: "string" }
          - { label: "Footer", name: "footer", widget: "object", fields: [
              { label: "Company Name", name: "company", widget: "string" },
              { label: "Address", name: "address", widget: "string" },
              { label: "Phone", name: "phone", widget: "string" },
              { label: "License Number", name: "license", widget: "string" },
              { label: "Instagram URL", name: "instagram", widget: "string", required: false },
              { label: "X/Twitter URL", name: "x", widget: "string", required: false }
            ]}
