backend:
  name: git-gateway
  branch: main

media_folder: "src/images"
public_folder: "/images"

collections:
  - name: 'homepage'
    label: 'Homepage'
    files:
      - file: 'src/_data/home.json'
        label: 'Homepage Content'
        name: 'home'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Hero Text', name: 'hero', widget: 'string' }
          - { label: 'Services', name: 'services', widget: 'list', fields: [
              { label: 'Title', name: 'title', widget: 'string' },
              { label: 'Description', name: 'desc', widget: 'text' }
            ]
          }
